# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aroi <marvin@42.fr>                        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/14 17:42:00 by aroi              #+#    #+#              #
#    Updated: 2018/07/26 11:23:57 by aroi             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= libft.a

CC		= gcc
CFLAGS	= -Wall -Werror -Wextra

SRC =	color.c \
		date_func.c \
		ft_atoi.c \
		ft_atoi_base.c \
		ft_bzero.c \
		ft_cast_act.c \
		ft_count_digits.c \
		ft_count_letters.c \
		ft_freearr.c \
		ft_delarr.c \
		ft_is.c \
		ft_is_sigil.c \
		ft_isalnum.c \
		ft_isalpha.c \
		ft_isascii.c \
		ft_isdigit.c \
		ft_ishex.c \
		ft_ishexnumber.c \
		ft_isnumber.c \
		ft_isprint.c \
		ft_itoa.c \
		ft_itoa_base.c \
		ft_lstadd.c \
		ft_lstaddend.c \
		ft_lstdel.c \
		ft_lstdelone.c \
		ft_lstiter.c \
		ft_lstmap.c \
		ft_lstnew.c \
		ft_memalloc.c \
		ft_memccpy.c \
		ft_memchr.c \
		ft_memcmp.c \
		ft_memcpy.c \
		ft_memdel.c \
		ft_memmove.c \
		ft_memset.c \
		ft_pow.c \
		ft_printf.c \
		ft_putchar.c \
		ft_putchar_fd.c \
		ft_putstr.c \
		ft_putstr_fd.c \
		ft_putendl.c \
		ft_putendl_fd.c \
		ft_putnbr.c \
		ft_putnbr_fd.c \
		ft_strcat.c \
		ft_strchr.c \
		ft_strclr.c \
		ft_strcmp.c \
		ft_strcpy.c \
		ft_strdel.c \
		ft_strdup.c \
		ft_strequ.c \
		ft_striter.c \
		ft_striteri.c \
		ft_strjoin.c \
		ft_strlcat.c \
		ft_strlcpy.c \
		ft_strlen.c \
		ft_strmap.c \
		ft_strmapi.c \
		ft_strncat.c \
		ft_strncmp.c \
		ft_strncpy.c \
		ft_strnequ.c \
		ft_strnew.c \
		ft_strnstr.c \
		ft_strrchr.c \
		ft_strsplit.c \
		ft_strsplittolist.c \
		ft_strstr.c \
		ft_strsub.c \
		ft_strtrim.c \
		ft_sqrt.c \
		ft_tolower.c \
		ft_toupper.c \
		ft_lower.c \
		ft_upper.c \
		ft_uitoa.c \
		ft_uitoa_base.c \
		get_next_line.c \
		out_b.c \
		out_base.c \
		out_bin_dec.c \
		out_c.c \
		out_date.c \
		out_int.c \
		out_uint.c \
		out_n.c \
		out_o.c \
		out_s.c \
		out_sqrt.c \
		out_xp_part_one.c \
		out_xp_prt_two.c \
		printf_func.c \
		qnt_of_bits.c \
		what_is.c \
		what_is_pt_two.c

OBJ =	color.o \
		date_func.o \
		ft_atoi.o \
		ft_atoi_base.o \
		ft_bzero.o \
		ft_cast_act.o \
		ft_count_digits.o \
		ft_count_letters.o \
		ft_delarr.o \
		ft_freearr.o \
		ft_is.o \
		ft_is_sigil.o \
		ft_isalnum.o \
		ft_isalpha.o \
		ft_isascii.o \
		ft_isdigit.o \
		ft_ishex.o \
		ft_ishexnumber.o \
		ft_isnumber.o \
		ft_isprint.o \
		ft_itoa.o \
		ft_itoa_base.o \
		ft_lstadd.o \
		ft_lstaddend.o \
		ft_lstdel.o \
		ft_lstdelone.o \
		ft_lstiter.o \
		ft_lstmap.o \
		ft_lstnew.o \
		ft_memalloc.o \
		ft_memccpy.o \
		ft_memchr.o \
		ft_memcmp.o \
		ft_memcpy.o \
		ft_memdel.o \
		ft_memmove.o \
		ft_memset.o \
		ft_pow.o \
		ft_printf.o \
		ft_putchar.o \
		ft_putchar_fd.o \
		ft_putstr.o \
		ft_putstr_fd.o \
		ft_putendl.o \
		ft_putendl_fd.o \
		ft_putnbr.o \
		ft_putnbr_fd.o \
		ft_strcat.o \
		ft_strchr.o \
		ft_strclr.o \
		ft_strcmp.o \
		ft_strcpy.o \
		ft_strdel.o \
		ft_strdup.o \
		ft_strequ.o \
		ft_striter.o \
		ft_striteri.o \
		ft_strjoin.o \
		ft_strlcat.o \
		ft_strlcpy.o \
		ft_strlen.o \
		ft_strmap.o \
		ft_strmapi.o \
		ft_strncat.o \
		ft_strncmp.o \
		ft_strncpy.o \
		ft_strnequ.o \
		ft_strnew.o \
		ft_strnstr.o \
		ft_strrchr.o \
		ft_strsplit.o \
		ft_strsplittolist.o \
		ft_strstr.o \
		ft_strsub.o \
		ft_strtrim.o \
		ft_sqrt.o \
		ft_tolower.o \
		ft_toupper.o \
		ft_lower.o \
		ft_upper.o \
		ft_uitoa.o \
		ft_uitoa_base.o \
		get_next_line.o \
		out_b.o \
		out_base.o \
		out_bin_dec.o \
		out_c.o \
		out_date.o \
		out_int.o \
		out_uint.o \
		out_n.o \
		out_o.o \
		out_s.o \
		out_sqrt.o \
		out_xp_prt_one.o \
		out_xp_prt_two.o \
		printf_func.o \
		qnt_of_bits.o \
		what_is.o \
		what_is_pt_two.o

%.o: %.c
	@$(CC) $(CFLAGS) -c -o $@ $<

all: $(NAME)

$(NAME): $(OBJ)
	@ar rcs $(NAME) $(OBJ)

clean:
	@rm -rf $(OBJ)

fclean: clean
	@rm -rf $(NAME)

re: fclean all
